Edited tooltips
WhoBrokeTheBuild/mdsplus-dtacq pull request #1
Opened 2023-03-24 15:56 UTC by wattea

Edited tooltips to be more explanatory

2023-03-30 18:44 UTC, WhoBrokeTheBuild requested changes

2023-03-30 18:44 UTC, WhoBrokeTheBuild commented on ACQ2106.py
> +                'tooltip': 'Options will decided if the timing highway is d0 or d1. For a soft trigger use STRIG, and for a hard trigger use EXT.',
This loses the text explaining that it is the trigger source

2023-03-30 18:44 UTC, WhoBrokeTheBuild commented on ACQ2106.py
> +                'tooltip': 'Contains settings for use when MODE=TRANSIENT.',
"for use with" is a very common term in documentation when describing options that depend on each other

2023-03-30 18:44 UTC, WhoBrokeTheBuild commented on ACQ2106.py
> +                'tooltip': 'Nanoseconds per tick of the clock, which is queried from the digitizer.',
The the is kind of important here, You could say "The number of nanoseconds per tick"

2023-04-27 14:04 UTC, santorofer requested changes

2023-04-27 14:04 UTC, santorofer commented on ACQ2106.py
> +                'tooltip': 'Options will decided if the timing highway is d0 or d1. For a soft trigger use STRIG, and for a hard trigger use EXT.',
I agree with Stephen. Also, it should probably say: "... will decide ..."

2023-04-27 14:04 UTC, santorofer commented on ACQ2106.py
>                      },
Should we say explicitly that these are default values in the tooltip?

2023-05-01 18:31 UTC, santorofer approved these changes

2023-05-17 20:39 UTC, WhoBrokeTheBuild approved these changes

2023-05-17 20:39 UTC, merged